### ISSUE TITLE
Security for command usage like `/kick`, `/stop`

### ISSUE THREAD

**Issue by ghost** [astrosonic/sanctuary#72]
The command `/kick` and `/stop` can be used by anyone in the room. This is not a good idea to give access to everyone for this command. How about implementing admin perms for a few people or the concept of host and members (just like the perms of room management in zoom).

You can add this to long term goals

**Comment by gridhead** [comment]
We can add the `/purr` option for all the users though. The remaining options have been kept open for testing purposes only and would be rolled back to be in the control of the room administrator only.

**Comment by ghost** [comment]
Sorry, if I was a disturbing soul.

**Comment by gridhead** [comment]
Hi @xcodz-dot,

I know it has been a long while since we last attended your issues/PRs and I understand that it can be disheartening to be in such a situation. We would definitely get back to working on this at a later date, whenever we would find some time out of the tasks we are usually engaged in. Thanks for contributing. :)

**Comment by ghost** [comment]
:)
