### ISSUE TITLE
PEP8 Automatic PR checks (Code Linting)

### ISSUE THREAD

**Issue by ghost** [astrosonic/sanctuary#73]
My goals:
* PEP8 action to ensure good and readable code when submitting a PR or pushing changes
* Format the already present code before implementing the action itself.

Other goals (I will be rasing issues for them after this):
* Add a CONTRIBUTING.md (A github file which instructs users how to work if they want to contribute)

**Comment by gridhead** [comment]
Thank you for creating this issue @xcodz-dot.

**Comment by ghost** [comment]
please assign this to me.

**Comment by gridhead** [comment]
@shivangswain@gmail.com <shivangswain@gmail.com> it would be helpful if you
could assign this issue.

Thanks.

**Comment by ghost** [comment]
Hello @shivangswain, please look at this #74, so i can apply further changes for code linting action

**Comment by gridhead** [comment]
Hi @xcodz-dot,

I know it has been a long while since we last attended your issues/PRs and I understand that it can be disheartening to be in such a situation. We would definitely get back to working on this at a later date, whenever we would find some time out of the tasks we are usually engaged in. Thanks for contributing. :)

**Comment by ghost** [comment]
:)
